services:
  frontend-dev:
    build:
      context: .
      target: dev
    container_name: sprint4-blink-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev -- --host 0.0.0.0 --port 5173

  frontend-prod:
    build:
      context: .
      target: production
    container_name: sprint4-blink-prod
    ports:
      - "8080:80"
    profiles:
      - prod
